database:
  development:
#   adapter: sqlite3
#   database: db/development.sqlite
    adapter: mysql2
    database: grab_feeling
    username: root
    password: password
  production:
    adapter: sqlite3
    database: db/production.sqlite

key_salt: insertsalthere

url:
  websocket: http://localhost:4568/
  ws: ws://localhost:4569/

websocket:
  port: 4569
  bind: 127.0.0.1
# socket: /tmp/the.sock
  timeout: 20
  ping_interval: 10

session:
  secret: pleasechangeme

operation:
  max_players: 10
  max_viewers: 10
  turn: 180 #sec
  interval: 10 #sec
  timeout_to_kick: 30 #sec

theme_opening:
  hider: "?"
  timings:
    60: 15
    120: 25
    150: 50

default_language: ja
