database:
  development:
#   adapter: sqlite3
#   database: db/development.sqlite
    adapter: mysql2
    database: grab_feeling
    username: root
    password: password
  production:
    adapter: sqlite3
    database: db/production.sqlite

key_salt: insertsalthere

url:
  websocket: http://localhost:4568/
  ws: ws://localhost:4569/

websocket:
# socket: /tmp/the.sock
  port: 4569
  bind: 127.0.0.1
  timeout: 20
  ping_interval: 10

operation:
  max_players: 10
  max_viewers: 20
  turn: 180 #sec

default_language: ja
