database:
  development:
    adapter: sqlite3
    database: db/development.sqlite
  production:
    adapter: sqlite3
    database: db/production.sqlite

key_salt: insertsalthere

url:
  websocket: http://localhost:4567/

websocket:
  socket: /tmp/the.sock
  port: 4566
  bind: 127.0.0.1

operation:
  max_players: 10
  max_viewers: 20
  turn: 180 #sec
